### ISSUE TITLE
google-translate--search-tkk: Search failed: ",tkk:'"

### ISSUE THREAD

**Issue by hongyi-zhao** [jcs-elpa/define-it#2] opened 2021-07-26 05:03 UTC
On Ubuntu 20.04, I try to use this package with the following configuration:

```emacs-lisp
(use-package define-it
  :config
  (setq ; Output with buffer.
        ;define-it-output-choice 'view 
        ; Output with tooltip.
        define-it-output-choice 'pop   
        ; Auto detect language.
        google-translate-default-source-language "auto" 
        ; Set your target language.
        google-translate-default-target-language "cn"))
```
But when I issue the command `M-x define-it-at-point RET`, the errors are triggered like the following:

![image](https://user-images.githubusercontent.com/11155854/126935410-1d18e735-193c-4088-bbe1-846792b32cb1.png)

Any hints for solving this problem?

Regards,
HY

**Comment by jcs090218** [comment] 2021-07-26 05:33
This is an upstream issue from `google-translate`, current workaround https://github.com/atykhonov/google-translate/issues/52#issuecomment-424302439.

**Comment by hongyi-zhao** [comment] 2021-07-26 06:53
Thank you for directing me to the upstream bug. Base on my tires, the above comment is invalid now, and the vaild one is this [comment](https://github.com/atykhonov/google-translate/issues/52#issuecomment-727920888).

**Comment by jcs090218** [comment] 2021-07-26 06:57
Thanks! Did not know it has changed! 👍

**Comment by hongyi-zhao** [comment] 2021-07-26 07:01
However, a more general approach should rely on the real-time generated tokens to use the Google Translate API, for example, through the following tools:

https://github.com/kyai/google-translate-tk
https://www.npmjs.com/package/google-translate-tk

The above tools are implemented with `golang` and `javascript` respectively, which I'm not familiar with. So I can't immediately give a try on them. Another one which is implemented in python:

https://github.com/ssut/py-googletrans/blob/master/googletrans/gtoken.py

**Comment by jcs090218** [comment] 2021-07-26 07:53
> However, a more general approach should rely on real-time generated tokens to use the Google Translate API, for example, through the following tools:

The goal of this project is to use a third party package written in Elisp due to the complexity and portability. Of course, we can implement that to this project but this requires some work and yet I do not have plan in a near future.

On the other hand, I would accept PRs if you are motivate on this enhancement. 👍

**Comment by jcs090218** [comment] 2021-07-26 07:55
I am going to close this issue due to the issue is from the upstream.

I have pinned this issue for people may have the same question.

**Closed as completed by jcs090218** 2021-07-26 07:55 UTC
Labels: upstream
